Set up database (Closes #5)
acmucsd/acmurl pull request #15
Opened 2019-07-26 07:26 UTC by jadenpadua

2019-07-26 07:43 UTC, eminguyen submitted a review, later dismissed
sorry one month at google has made me be a lot more strict about comments

2019-07-27 19:47 UTC, ClarkPhan approved these changes

2019-07-27 21:11 UTC, eminguyen requested changes
looks good, you just need to squash your commits

2019-07-27 21:25 UTC, eminguyen approved these changes

2019-07-27 21:50 UTC, merged